### ISSUE TITLE
my_uuid=$(uuidgen) ?

### ISSUE THREAD

**Issue by sebastienvg** [breunigs/bravia-auth-and-remote#2]
how do I get this my_uuid=$(uuidgen) ?

**Comment by sebastienvg** [comment]
when I try 

`./send_command.sh 192.168.77.8 AAAAAQAAAAEAAAAvAw==` to turn off the TV I get

`Command failed (HTTP_CODE: 500, try running it in a console)`

**Comment by breunigs** [comment]
Did the auth process work properly, like described in the blog post? 

If not, run the commands from the script manually in verbose mode to figure out where it fails.

You can use https://www.uuidgenerator.net/ Do generate any uuid if you can't install a generator on your machine. The only goal for it is to be unique for your tv (I.e. Not yet used by any connected app)

**Comment by sebastienvg** [comment]
You've nailed it. I got a uuid added to the file then ran the auth.sh again and all worked fine.

Thank you

**Comment by chrlymurphy** [comment]
I have tried to add a UUID using this method and looking at an incoming UDP packet from the tv.  I get the same error on both occasions:

auth.sh: 16: auth.sh xxx-xxx-x--x-x---x-x--x: not found

sub any UUID i try for the xxx-xxx....

Any suggestions?

**Comment by breunigs** [comment]
You need to write it like `my_uuid=$(abcdef-bla-bla)`

**Comment by chrlymurphy** [comment]
Thanks for the Reply B.  WIthin the code, it is:
my_uuid=$(97cb9b2e-7327-4333-a757-c5b19a9380a5)

Error is:
auth.sh: 16: auth.sh: 97cb9b2e-7327-4333-a757-c5b19a9380a5: not found

**Comment by chrlymurphy** [comment]
I didn't have the single quotes.  I added them and it worked.  Thanks!!!

my_uuid='$(97cb9b2e-7327-4333-a757-c5b19a9380a5)'
