### ISSUE TITLE
Windows Problem :)

### ISSUE THREAD

**Issue by scupnet** [breunigs/bravia-auth-and-remote#3]
Hi, 
i would like to use your script with Windows Powershell 
it works fine until i type in the PIN that is showed on the TV
then i recieve this error:
auth.sh: line 46: base64: command not found
is it possible to made powershell (via github for windows) to understand the line 46?
OS is Windows10

there was also an issue in line 11 with the uuidgen command 
-that could be solved  in this way that i define my own uuid like my_uuid=123456

**Comment by breunigs** [comment]
hi, 

i assume you can find these programs for download on the internet and put them either in the same directory or somewhere else in your $PATH. for details on how to do this please refer to documentation on the internet.

**Comment by scupnet** [comment]
good morning,

so i have to look for base64 tool? i am really a noob and script kiddie and did my last coding in basic a long time ago on my sinclair z3.. would you post a link to a documentaion that helps me please :)
I know this was going much easier if i run the script on my linux mint laptop but i wanna authentificate my Windows Desktop. 

An alternative way was ist if you could Post the two Commands here, that one that start the handshake with the TV, and that one that submits the PIN to the TV. 

So i could use the Advanced Rest Client to talk to the TV

Kind Regards,
Christoph

**Comment by breunigs** [comment]
you can use your linux machine to authenticate and then just copy the auth file it creates. 

i have no idea if the "use" script will run on Windows. 

I cannot give you any hints for Windows, since I don't use that platform.

**Comment by scupnet** [comment]
okay i will try that way, i thought that the mac adress is also a factor for the authentification process..
many thanx

**Comment by breunigs** [comment]
eugh, it might. I didnt try it when writing this and the TV might also check the Mac. however, the "macchanger" tool should be available on most linux distributions
