### ISSUE TITLE
Unable to set up PSK on Bravia W9 

### ISSUE THREAD

**Issue by CoooolRaoul** [breunigs/bravia-auth-and-remote#9]
On my KDL-46W905A there is no _"IP Control"_ item under _"Settings"_ -> _"Network"_ -> _"Home Network Setup"_

Remote commands works using cookie though. But does this implies that I will face the 2/3 weeks expiration or could by chance this issue applies only to newer models?

**Comment by breunigs** [comment]
I don’t know, I guess the only way to be sure is to test it.

However, it seems that the challenge the TV gives you does not change over time, so you should be able to change the `0000` value to whatever code the TV shows (in send_command.sh). You can use the auth.sh trigger the dialog.

**Comment by CoooolRaoul** [comment]
>  so you should be able to change the 0000 value to whatever code the TV shows (in send_command.sh). 

Thanks! seem to be working.
